name: platform_serial
description: >
  Complete Flutter plugin for managing serial ports.
  Supports Windows, Linux, macOS, Android (OTG), and iOS (OTG) with a unified interface.
  Provides synchronous and asynchronous communication, support for both binary and textual data, and comprehensive error handling.


version: 0.1.0
homepage: https://github.com/pvagnozzi/platform_serial
repository: https://github.com/pvagnozzi/platform_serial
issue_tracker: https://github.com/pvagnozzi/platform_serial/issues
documentation: https://github.com/pvagnozzi/platform_serial/tree/main/doc

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.0
  mocktail: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.xauron.platform_serial
        pluginClass: FlutterSerialPlugin
      ios:
        pluginClass: FlutterSerialPlugin
      linux:
        pluginClass: FlutterSerialPlugin
        ffiPlugin: true
      macos:
        ffiPlugin: true
      windows:
        ffiPlugin: true
