// Copyright (c) 2026 Piergiorgio Vagnozzi.
// Licensed under the MIT License.
import 'package:flutter/widgets.dart';

class AppLocalizations {
  AppLocalizations(this.locale);

  final Locale locale;

  static const List<Locale> supportedLocales = <Locale>[
    Locale('en'),
    Locale('fr'),
    Locale('pt'),
    Locale('es'),
    Locale('it'),
    Locale('de'),
    Locale('nl'),
    Locale('ru'),
    Locale('el'),
    Locale('tr'),
    Locale('ar'),
    Locale('he'),
    Locale('zh'),
    Locale('ja'),
    Locale('ko'),
  ];

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static const Map<String, String> localeLabels = <String, String>{
    'en': 'English',
    'fr': 'Français',
    'pt': 'Português',
    'es': 'Español',
    'it': 'Italiano',
    'de': 'Deutsch',
    'nl': 'Nederlands',
    'ru': 'Русский',
    'el': 'Ελληνικά',
    'tr': 'Türkçe',
    'ar': 'العربية',
    'he': 'עברית',
    'zh': '中文',
    'ja': '日本語',
    'ko': '한국어',
  };

  static const Map<String, String> localeFlags = <String, String>{
    'en': '🇬🇧',
    'fr': '🇫🇷',
    'pt': '🇵🇹',
    'es': '🇪🇸',
    'it': '🇮🇹',
    'de': '🇩🇪',
    'nl': '🇳🇱',
    'ru': '🇷🇺',
    'el': '🇬🇷',
    'tr': '🇹🇷',
    'ar': '🇸🇦',
    'he': '🇮🇱',
    'zh': '🇨🇳',
    'ja': '🇯🇵',
    'ko': '🇰🇷',
  };

  static const Set<String> _rtlLanguages = <String>{'ar', 'he'};

  bool get isRtl => _rtlLanguages.contains(locale.languageCode);

  String get languageCode => locale.languageCode;

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  static const Map<String, Map<String, String>> _localizedValues =
      <String, Map<String, String>>{
    'en': <String, String>{
      'appTitle': 'Platform Serial Terminal',
      'splashSubtitle': 'Professional serial communication console',
      'refreshPorts': 'Refresh ports',
      'serialParameters': 'Serial parameters',
      'port': 'Port',
      'baudRate': 'Baud rate',
      'dataBits': 'Data bits',
      'stopBits': 'Stop bits',
      'parity': 'Parity',
      'flowControl': 'Flow control',
      'readTimeoutMs': 'Read timeout (ms)',
      'writeTimeoutMs': 'Write timeout (ms)',
      'open': 'Open',
      'close': 'Close',
      'clear': 'Clear',
      'terminal': 'Terminal',
      'inputPlaceholder': 'Type data to send...',
      'send': 'Send',
      'disconnected': 'Disconnected',
      'connectedTo': 'Connected to {port}',
      'incoming': 'Incoming',
      'outgoing': 'Outgoing',
      'system': 'System',
      'error': 'Error',
      'about': 'About',
      'appDescription': 'Cross-platform serial terminal built with Flutter.',
      'copyright': 'Copyright (c) 2026 Piergiorgio Vagnozzi',
      'licenses': 'Licenses',
      'noPorts': 'No serial ports found.',
      'openingFailed': 'Failed to open the selected port.',
      'closingFailed': 'Failed to close the active port.',
      'sendFailed': 'Failed to send data.',
      'chooseLanguage': 'Language',
    },
    'fr': <String, String>{
      'appTitle': 'Terminal Série Platform',
      'splashSubtitle': 'Console professionnelle de communication série',
      'refreshPorts': 'Actualiser les ports',
      'serialParameters': 'Paramètres série',
      'port': 'Port',
      'baudRate': 'Débit',
      'dataBits': 'Bits de données',
      'stopBits': 'Bits d’arrêt',
      'parity': 'Parité',
      'flowControl': 'Contrôle de flux',
      'readTimeoutMs': 'Délai lecture (ms)',
      'writeTimeoutMs': 'Délai écriture (ms)',
      'open': 'Ouvrir',
      'close': 'Fermer',
      'clear': 'Effacer',
      'terminal': 'Terminal',
      'inputPlaceholder': 'Saisissez les données à envoyer...',
      'send': 'Envoyer',
      'disconnected': 'Déconnecté',
      'connectedTo': 'Connecté à {port}',
      'incoming': 'Entrant',
      'outgoing': 'Sortant',
      'system': 'Système',
      'error': 'Erreur',
      'about': 'À propos',
      'appDescription':
          'Terminal série multiplateforme développé avec Flutter.',
      'copyright': 'Copyright (c) 2026 Piergiorgio Vagnozzi',
      'licenses': 'Licences',
      'noPorts': 'Aucun port série trouvé.',
      'openingFailed': 'Impossible d’ouvrir le port sélectionné.',
      'closingFailed': 'Impossible de fermer le port actif.',
      'sendFailed': 'Échec de l’envoi des données.',
      'chooseLanguage': 'Langue',
    },
    'pt': <String, String>{
      'appTitle': 'Terminal Serial Platform',
      'splashSubtitle': 'Console profissional de comunicação serial',
      'refreshPorts': 'Atualizar portas',
      'serialParameters': 'Parâmetros seriais',
      'port': 'Porta',
      'baudRate': 'Taxa de baud',
      'dataBits': 'Bits de dados',
      'stopBits': 'Bits de parada',
      'parity': 'Paridade',
      'flowControl': 'Controle de fluxo',
      'readTimeoutMs': 'Timeout de leitura (ms)',
      'writeTimeoutMs': 'Timeout de escrita (ms)',
      'open': 'Abrir',
      'close': 'Fechar',
      'clear': 'Limpar',
      'terminal': 'Terminal',
      'inputPlaceholder': 'Digite dados para enviar...',
      'send': 'Enviar',
      'disconnected': 'Desconectado',
      'connectedTo': 'Conectado a {port}',
      'incoming': 'Entrada',
      'outgoing': 'Saída',
      'system': 'Sistema',
      'error': 'Erro',
      'about': 'Sobre',
      'appDescription': 'Terminal serial multiplataforma em Flutter.',
      'copyright': 'Copyright (c) 2026 Piergiorgio Vagnozzi',
      'licenses': 'Licenças',
      'noPorts': 'Nenhuma porta serial encontrada.',
      'openingFailed': 'Falha ao abrir a porta selecionada.',
      'closingFailed': 'Falha ao fechar a porta ativa.',
      'sendFailed': 'Falha ao enviar dados.',
      'chooseLanguage': 'Idioma',
    },
    'es': <String, String>{
      'appTitle': 'Terminal Serie Platform',
      'splashSubtitle': 'Consola profesional de comunicación serie',
      'refreshPorts': 'Actualizar puertos',
      'serialParameters': 'Parámetros serie',
      'port': 'Puerto',
      'baudRate': 'Baud rate',
      'dataBits': 'Bits de datos',
      'stopBits': 'Bits de parada',
      'parity': 'Paridad',
      'flowControl': 'Control de flujo',
      'readTimeoutMs': 'Tiempo lectura (ms)',
      'writeTimeoutMs': 'Tiempo escritura (ms)',
      'open': 'Abrir',
      'close': 'Cerrar',
      'clear': 'Limpiar',
      'terminal': 'Terminal',
      'inputPlaceholder': 'Escribe datos para enviar...',
      'send': 'Enviar',
      'disconnected': 'Desconectado',
      'connectedTo': 'Conectado a {port}',
      'incoming': 'Entrada',
      'outgoing': 'Salida',
      'system': 'Sistema',
      'error': 'Error',
      'about': 'Acerca de',
      'appDescription': 'Terminal serie multiplataforma creado con Flutter.',
      'copyright': 'Copyright (c) 2026 Piergiorgio Vagnozzi',
      'licenses': 'Licencias',
      'noPorts': 'No se encontraron puertos serie.',
      'openingFailed': 'No se pudo abrir el puerto seleccionado.',
      'closingFailed': 'No se pudo cerrar el puerto activo.',
      'sendFailed': 'No se pudieron enviar los datos.',
      'chooseLanguage': 'Idioma',
    },
    'it': <String, String>{
      'appTitle': 'Terminale Seriale Platform',
      'splashSubtitle': 'Console professionale per comunicazione seriale',
      'refreshPorts': 'Aggiorna porte',
      'serialParameters': 'Parametri seriali',
      'port': 'Porta',
      'baudRate': 'Baud rate',
      'dataBits': 'Bit dati',
      'stopBits': 'Bit di stop',
      'parity': 'Parità',
      'flowControl': 'Controllo di flusso',
      'readTimeoutMs': 'Timeout lettura (ms)',
      'writeTimeoutMs': 'Timeout scrittura (ms)',
      'open': 'Apri',
      'close': 'Chiudi',
      'clear': 'Pulisci',
      'terminal': 'Terminale',
      'inputPlaceholder': 'Digita i dati da inviare...',
      'send': 'Invia',
      'disconnected': 'Disconnesso',
      'connectedTo': 'Connesso a {port}',
      'incoming': 'Ingresso',
      'outgoing': 'Uscita',
      'system': 'Sistema',
      'error': 'Errore',
      'about': 'Informazioni',
      'appDescription':
          'Terminale seriale multipiattaforma sviluppato con Flutter.',
      'copyright': 'Copyright (c) 2026 Piergiorgio Vagnozzi',
      'licenses': 'Licenze',
      'noPorts': 'Nessuna porta seriale trovata.',
      'openingFailed': 'Impossibile aprire la porta selezionata.',
      'closingFailed': 'Impossibile chiudere la porta attiva.',
      'sendFailed': 'Invio dati non riuscito.',
      'chooseLanguage': 'Lingua',
    },
    'de': <String, String>{
      'appTitle': 'Platform Serial Terminal',
      'splashSubtitle': 'Professionelle serielle Kommunikationskonsole',
      'refreshPorts': 'Ports aktualisieren',
      'serialParameters': 'Serielle Parameter',
      'port': 'Port',
      'baudRate': 'Baudrate',
      'dataBits': 'Datenbits',
      'stopBits': 'Stoppbits',
      'parity': 'Parität',
      'flowControl': 'Flusskontrolle',
      'readTimeoutMs': 'Lese-Timeout (ms)',
      'writeTimeoutMs': 'Schreib-Timeout (ms)',
      'open': 'Öffnen',
      'close': 'Schließen',
      'clear': 'Leeren',
      'terminal': 'Terminal',
      'inputPlaceholder': 'Daten zum Senden eingeben...',
      'send': 'Senden',
      'disconnected': 'Getrennt',
      'connectedTo': 'Verbunden mit {port}',
      'incoming': 'Eingehend',
      'outgoing': 'Ausgehend',
      'system': 'System',
      'error': 'Fehler',
      'about': 'Info',
      'appDescription':
          'Plattformübergreifendes serielles Terminal mit Flutter.',
      'copyright': 'Copyright (c) 2026 Piergiorgio Vagnozzi',
      'licenses': 'Lizenzen',
      'noPorts': 'Keine seriellen Ports gefunden.',
      'openingFailed': 'Öffnen des Ports fehlgeschlagen.',
      'closingFailed': 'Schließen des Ports fehlgeschlagen.',
      'sendFailed': 'Senden fehlgeschlagen.',
      'chooseLanguage': 'Sprache',
    },
    'nl': <String, String>{
      'appTitle': 'Platform Seriële Terminal',
      'splashSubtitle': 'Professionele seriële communicatieconsole',
      'refreshPorts': 'Poorten vernieuwen',
      'serialParameters': 'Seriële parameters',
      'port': 'Poort',
      'baudRate': 'Baudrate',
      'dataBits': 'Databits',
      'stopBits': 'Stopbits',
      'parity': 'Pariteit',
      'flowControl': 'Flow control',
      'readTimeoutMs': 'Lees-time-out (ms)',
      'writeTimeoutMs': 'Schrijf-time-out (ms)',
      'open': 'Openen',
      'close': 'Sluiten',
      'clear': 'Wissen',
      'terminal': 'Terminal',
      'inputPlaceholder': 'Typ gegevens om te verzenden...',
      'send': 'Verzenden',
      'disconnected': 'Niet verbonden',
      'connectedTo': 'Verbonden met {port}',
      'incoming': 'Inkomend',
      'outgoing': 'Uitgaand',
      'system': 'Systeem',
      'error': 'Fout',
      'about': 'Over',
      'appDescription': 'Cross-platform seriële terminal gebouwd met Flutter.',
      'copyright': 'Copyright (c) 2026 Piergiorgio Vagnozzi',
      'licenses': 'Licenties',
      'noPorts': 'Geen seriële poorten gevonden.',
      'openingFailed': 'Openen van de poort mislukt.',
      'closingFailed': 'Sluiten van de poort mislukt.',
      'sendFailed': 'Verzenden mislukt.',
      'chooseLanguage': 'Taal',
    },
    'ru': <String, String>{
      'appTitle': 'Серийный терминал Platform',
      'splashSubtitle': 'Профессиональная консоль последовательной связи',
      'refreshPorts': 'Обновить порты',
      'serialParameters': 'Параметры порта',
      'port': 'Порт',
      'baudRate': 'Скорость',
      'dataBits': 'Биты данных',
      'stopBits': 'Стоп-биты',
      'parity': 'Четность',
      'flowControl': 'Управление потоком',
      'readTimeoutMs': 'Тайм-аут чтения (мс)',
      'writeTimeoutMs': 'Тайм-аут записи (мс)',
      'open': 'Открыть',
      'close': 'Закрыть',
      'clear': 'Очистить',
      'terminal': 'Терминал',
      'inputPlaceholder': 'Введите данные для отправки...',
      'send': 'Отправить',
      'disconnected': 'Отключено',
      'connectedTo': 'Подключено к {port}',
      'incoming': 'Входящие',
      'outgoing': 'Исходящие',
      'system': 'Система',
      'error': 'Ошибка',
      'about': 'О приложении',
      'appDescription': 'Кроссплатформенный серийный терминал на Flutter.',
      'copyright': 'Copyright (c) 2026 Piergiorgio Vagnozzi',
      'licenses': 'Лицензии',
      'noPorts': 'Серийные порты не найдены.',
      'openingFailed': 'Не удалось открыть выбранный порт.',
      'closingFailed': 'Не удалось закрыть активный порт.',
      'sendFailed': 'Не удалось отправить данные.',
      'chooseLanguage': 'Язык',
    },
    'el': <String, String>{
      'appTitle': 'Σειριακό Τερματικό Platform',
      'splashSubtitle': 'Επαγγελματική κονσόλα σειριακής επικοινωνίας',
      'refreshPorts': 'Ανανέωση θυρών',
      'serialParameters': 'Σειριακές παράμετροι',
      'port': 'Θύρα',
      'baudRate': 'Ρυθμός baud',
      'dataBits': 'Bit δεδομένων',
      'stopBits': 'Bit τερματισμού',
      'parity': 'Ισοτιμία',
      'flowControl': 'Έλεγχος ροής',
      'readTimeoutMs': 'Χρονικό όριο ανάγνωσης (ms)',
      'writeTimeoutMs': 'Χρονικό όριο εγγραφής (ms)',
      'open': 'Άνοιγμα',
      'close': 'Κλείσιμο',
      'clear': 'Καθαρισμός',
      'terminal': 'Τερματικό',
      'inputPlaceholder': 'Πληκτρολογήστε δεδομένα για αποστολή...',
      'send': 'Αποστολή',
      'disconnected': 'Αποσυνδεδεμένο',
      'connectedTo': 'Συνδεδεμένο με {port}',
      'incoming': 'Εισερχόμενα',
      'outgoing': 'Εξερχόμενα',
      'system': 'Σύστημα',
      'error': 'Σφάλμα',
      'about': 'Πληροφορίες',
      'appDescription': 'Πολυπλατφορμικό σειριακό τερματικό με Flutter.',
      'copyright': 'Copyright (c) 2026 Piergiorgio Vagnozzi',
      'licenses': 'Άδειες',
      'noPorts': 'Δεν βρέθηκαν σειριακές θύρες.',
      'openingFailed': 'Αποτυχία ανοίγματος της επιλεγμένης θύρας.',
      'closingFailed': 'Αποτυχία κλεισίματος της ενεργής θύρας.',
      'sendFailed': 'Αποτυχία αποστολής δεδομένων.',
      'chooseLanguage': 'Γλώσσα',
    },
    'tr': <String, String>{
      'appTitle': 'Platform Seri Terminal',
      'splashSubtitle': 'Profesyonel seri iletişim konsolu',
      'refreshPorts': 'Portları yenile',
      'serialParameters': 'Seri parametreleri',
      'port': 'Port',
      'baudRate': 'Baud hızı',
      'dataBits': 'Veri bitleri',
      'stopBits': 'Dur bitleri',
      'parity': 'Eşlik',
      'flowControl': 'Akış kontrolü',
      'readTimeoutMs': 'Okuma zaman aşımı (ms)',
      'writeTimeoutMs': 'Yazma zaman aşımı (ms)',
      'open': 'Aç',
      'close': 'Kapat',
      'clear': 'Temizle',
      'terminal': 'Terminal',
      'inputPlaceholder': 'Gönderilecek veriyi yazın...',
      'send': 'Gönder',
      'disconnected': 'Bağlantı yok',
      'connectedTo': '{port} bağlantısı kuruldu',
      'incoming': 'Gelen',
      'outgoing': 'Giden',
      'system': 'Sistem',
      'error': 'Hata',
      'about': 'Hakkında',
      'appDescription':
          'Flutter ile geliştirilen çok platformlu seri terminal.',
      'copyright': 'Copyright (c) 2026 Piergiorgio Vagnozzi',
      'licenses': 'Lisanslar',
      'noPorts': 'Seri port bulunamadı.',
      'openingFailed': 'Seçilen port açılamadı.',
      'closingFailed': 'Etkin port kapatılamadı.',
      'sendFailed': 'Veri gönderilemedi.',
      'chooseLanguage': 'Dil',
    },
    'ar': <String, String>{
      'appTitle': 'طرفية Platform التسلسلية',
      'splashSubtitle': 'وحدة احترافية للاتصال التسلسلي',
      'refreshPorts': 'تحديث المنافذ',
      'serialParameters': 'إعدادات المنفذ',
      'port': 'المنفذ',
      'baudRate': 'معدل البود',
      'dataBits': 'بتات البيانات',
      'stopBits': 'بتات الإيقاف',
      'parity': 'التكافؤ',
      'flowControl': 'التحكم بالتدفق',
      'readTimeoutMs': 'مهلة القراءة (مللي ثانية)',
      'writeTimeoutMs': 'مهلة الكتابة (مللي ثانية)',
      'open': 'فتح',
      'close': 'إغلاق',
      'clear': 'مسح',
      'terminal': 'الطرفية',
      'inputPlaceholder': 'اكتب البيانات للإرسال...',
      'send': 'إرسال',
      'disconnected': 'غير متصل',
      'connectedTo': 'متصل مع {port}',
      'incoming': 'وارد',
      'outgoing': 'صادر',
      'system': 'النظام',
      'error': 'خطأ',
      'about': 'حول',
      'appDescription': 'طرفية تسلسلية متعددة المنصات مبنية بـ Flutter.',
      'copyright': 'Copyright (c) 2026 Piergiorgio Vagnozzi',
      'licenses': 'التراخيص',
      'noPorts': 'لم يتم العثور على منافذ تسلسلية.',
      'openingFailed': 'تعذر فتح المنفذ المحدد.',
      'closingFailed': 'تعذر إغلاق المنفذ النشط.',
      'sendFailed': 'تعذر إرسال البيانات.',
      'chooseLanguage': 'اللغة',
    },
    'he': <String, String>{
      'appTitle': 'מסוף טורי Platform',
      'splashSubtitle': 'קונסולת תקשורת טורית מקצועית',
      'refreshPorts': 'רענון פורטים',
      'serialParameters': 'פרמטרים טוריים',
      'port': 'פורט',
      'baudRate': 'קצב באוד',
      'dataBits': 'ביטי נתונים',
      'stopBits': 'ביטי עצירה',
      'parity': 'זוגיות',
      'flowControl': 'בקרת זרימה',
      'readTimeoutMs': 'פסק זמן קריאה (ms)',
      'writeTimeoutMs': 'פסק זמן כתיבה (ms)',
      'open': 'פתח',
      'close': 'סגור',
      'clear': 'נקה',
      'terminal': 'מסוף',
      'inputPlaceholder': 'הקלד נתונים לשליחה...',
      'send': 'שלח',
      'disconnected': 'מנותק',
      'connectedTo': 'מחובר אל {port}',
      'incoming': 'נכנס',
      'outgoing': 'יוצא',
      'system': 'מערכת',
      'error': 'שגיאה',
      'about': 'אודות',
      'appDescription': 'מסוף טורי רב-פלטפורמי שנבנה עם Flutter.',
      'copyright': 'Copyright (c) 2026 Piergiorgio Vagnozzi',
      'licenses': 'רישיונות',
      'noPorts': 'לא נמצאו פורטים טוריים.',
      'openingFailed': 'פתיחת הפורט שנבחר נכשלה.',
      'closingFailed': 'סגירת הפורט הפעיל נכשלה.',
      'sendFailed': 'שליחת הנתונים נכשלה.',
      'chooseLanguage': 'שפה',
    },
    'zh': <String, String>{
      'appTitle': 'Platform 串口终端',
      'splashSubtitle': '专业串口通信控制台',
      'refreshPorts': '刷新端口',
      'serialParameters': '串口参数',
      'port': '端口',
      'baudRate': '波特率',
      'dataBits': '数据位',
      'stopBits': '停止位',
      'parity': '校验',
      'flowControl': '流控',
      'readTimeoutMs': '读取超时 (ms)',
      'writeTimeoutMs': '写入超时 (ms)',
      'open': '打开',
      'close': '关闭',
      'clear': '清空',
      'terminal': '终端',
      'inputPlaceholder': '输入要发送的数据...',
      'send': '发送',
      'disconnected': '未连接',
      'connectedTo': '已连接到 {port}',
      'incoming': '接收',
      'outgoing': '发送',
      'system': '系统',
      'error': '错误',
      'about': '关于',
      'appDescription': '基于 Flutter 的跨平台串口终端。',
      'copyright': 'Copyright (c) 2026 Piergiorgio Vagnozzi',
      'licenses': '许可证',
      'noPorts': '未找到串口。',
      'openingFailed': '打开所选端口失败。',
      'closingFailed': '关闭当前端口失败。',
      'sendFailed': '发送数据失败。',
      'chooseLanguage': '语言',
    },
    'ja': <String, String>{
      'appTitle': 'Platform シリアルターミナル',
      'splashSubtitle': 'プロフェッショナルなシリアル通信コンソール',
      'refreshPorts': 'ポートを更新',
      'serialParameters': 'シリアル設定',
      'port': 'ポート',
      'baudRate': 'ボーレート',
      'dataBits': 'データビット',
      'stopBits': 'ストップビット',
      'parity': 'パリティ',
      'flowControl': 'フロー制御',
      'readTimeoutMs': '読み取りタイムアウト (ms)',
      'writeTimeoutMs': '書き込みタイムアウト (ms)',
      'open': '開く',
      'close': '閉じる',
      'clear': 'クリア',
      'terminal': 'ターミナル',
      'inputPlaceholder': '送信するデータを入力...',
      'send': '送信',
      'disconnected': '未接続',
      'connectedTo': '{port} に接続中',
      'incoming': '受信',
      'outgoing': '送信',
      'system': 'システム',
      'error': 'エラー',
      'about': '情報',
      'appDescription': 'Flutter で構築したクロスプラットフォームのシリアルターミナル。',
      'copyright': 'Copyright (c) 2026 Piergiorgio Vagnozzi',
      'licenses': 'ライセンス',
      'noPorts': 'シリアルポートが見つかりません。',
      'openingFailed': '選択したポートを開けませんでした。',
      'closingFailed': 'アクティブなポートを閉じられませんでした。',
      'sendFailed': 'データ送信に失敗しました。',
      'chooseLanguage': '言語',
    },
    'ko': <String, String>{
      'appTitle': 'Platform 시리얼 터미널',
      'splashSubtitle': '전문 시리얼 통신 콘솔',
      'refreshPorts': '포트 새로고침',
      'serialParameters': '시리얼 매개변수',
      'port': '포트',
      'baudRate': '보드레이트',
      'dataBits': '데이터 비트',
      'stopBits': '정지 비트',
      'parity': '패리티',
      'flowControl': '흐름 제어',
      'readTimeoutMs': '읽기 시간 초과 (ms)',
      'writeTimeoutMs': '쓰기 시간 초과 (ms)',
      'open': '열기',
      'close': '닫기',
      'clear': '지우기',
      'terminal': '터미널',
      'inputPlaceholder': '전송할 데이터를 입력하세요...',
      'send': '전송',
      'disconnected': '연결 해제됨',
      'connectedTo': '{port}에 연결됨',
      'incoming': '수신',
      'outgoing': '송신',
      'system': '시스템',
      'error': '오류',
      'about': '정보',
      'appDescription': 'Flutter로 구축한 크로스플랫폼 시리얼 터미널.',
      'copyright': 'Copyright (c) 2026 Piergiorgio Vagnozzi',
      'licenses': '라이선스',
      'noPorts': '시리얼 포트를 찾을 수 없습니다.',
      'openingFailed': '선택한 포트를 열 수 없습니다.',
      'closingFailed': '활성 포트를 닫을 수 없습니다.',
      'sendFailed': '데이터 전송에 실패했습니다.',
      'chooseLanguage': '언어',
    },
  };

  String _lookup(String key) {
    return _localizedValues[locale.languageCode]?[key] ??
        _localizedValues['en']![key]!;
  }

  String get appTitle => _lookup('appTitle');
  String get splashSubtitle => _lookup('splashSubtitle');
  String get refreshPorts => _lookup('refreshPorts');
  String get serialParameters => _lookup('serialParameters');
  String get port => _lookup('port');
  String get baudRate => _lookup('baudRate');
  String get dataBits => _lookup('dataBits');
  String get stopBits => _lookup('stopBits');
  String get parity => _lookup('parity');
  String get flowControl => _lookup('flowControl');
  String get readTimeoutMs => _lookup('readTimeoutMs');
  String get writeTimeoutMs => _lookup('writeTimeoutMs');
  String get open => _lookup('open');
  String get close => _lookup('close');
  String get clear => _lookup('clear');
  String get terminal => _lookup('terminal');
  String get inputPlaceholder => _lookup('inputPlaceholder');
  String get send => _lookup('send');
  String get disconnected => _lookup('disconnected');
  String get incoming => _lookup('incoming');
  String get outgoing => _lookup('outgoing');
  String get system => _lookup('system');
  String get error => _lookup('error');
  String get about => _lookup('about');
  String get appDescription => _lookup('appDescription');
  String get copyright => _lookup('copyright');
  String get licenses => _lookup('licenses');
  String get noPorts => _lookup('noPorts');
  String get openingFailed => _lookup('openingFailed');
  String get closingFailed => _lookup('closingFailed');
  String get sendFailed => _lookup('sendFailed');
  String get chooseLanguage => _lookup('chooseLanguage');

  String connectedTo(String portName) {
    return _lookup('connectedTo').replaceAll('{port}', portName);
  }
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return AppLocalizations.supportedLocales
        .map((Locale item) => item.languageCode)
        .contains(locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(covariant LocalizationsDelegate<AppLocalizations> old) {
    return false;
  }
}
